import type { CampaignResponse } from "../campaign.ts";
import { parseIsoDate as d } from "../dates.ts";
import { parseMoney4 as m } from "../money.ts";

export const nvdlCampaign: CampaignResponse = {
  id: "nvdl-campaign",
  title: "NVDL puts + NVDA hedge",
  openedOn: d("2026-09-15"),
  closedOn: null,
  notes: null,
  asOf: d("2026-10-01"),
  assignments: [],
  positions: [
    {
      id: "nvdl-75",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "NVDL",
      strategy: "csp",
      role: "income",
      openedOn: d("2026-09-15"),
      closedOn: null,
      notes: null,
      tags: [],
      legs: [
        {
          id: "nvdl-75-put",
          kind: "put",
          side: "short",
          underlying: "NVDL",
          strike: m("75"),
          expiry: d("2026-10-16"),
          multiplier: 100,
          adjusted: false,
          mark: null,
          trades: [
            {
              id: "nvdl-75-open",
              action: "open",
              tradeDate: d("2026-09-15"),
              quantity: 5,
              price: m("2.80"),
              cash: m("1400"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
    {
      id: "nvdl-70",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "NVDL",
      strategy: "csp",
      role: "income",
      openedOn: d("2026-09-15"),
      closedOn: null,
      notes: null,
      tags: [],
      legs: [
        {
          id: "nvdl-70-put",
          kind: "put",
          side: "short",
          underlying: "NVDL",
          strike: m("70"),
          expiry: d("2026-10-16"),
          multiplier: 100,
          adjusted: false,
          mark: null,
          trades: [
            {
              id: "nvdl-70-open",
              action: "open",
              tradeDate: d("2026-09-15"),
              quantity: 5,
              price: m("1.90"),
              cash: m("950"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
    {
      id: "nvda-hedge",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "NVDA",
      strategy: "put_debit_spread",
      role: "hedge",
      openedOn: d("2026-09-15"),
      closedOn: null,
      notes: null,
      tags: [],
      legs: [
        {
          id: "nvda-long-put",
          kind: "put",
          side: "long",
          underlying: "NVDA",
          strike: m("180"),
          expiry: d("2026-10-16"),
          multiplier: 100,
          adjusted: false,
          mark: null,
          trades: [
            {
              id: "nvda-long-open",
              action: "open",
              tradeDate: d("2026-09-15"),
              quantity: 2,
              price: m("1.09"),
              cash: m("-218"),
              fees: m("0"),
            },
          ],
        },
        {
          id: "nvda-short-put",
          kind: "put",
          side: "short",
          underlying: "NVDA",
          strike: m("175"),
          expiry: d("2026-10-16"),
          multiplier: 100,
          adjusted: false,
          mark: null,
          trades: [
            {
              id: "nvda-short-open",
              action: "open",
              tradeDate: d("2026-09-15"),
              quantity: 2,
              price: m("0"),
              cash: m("0"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
  ],
};

/** Synthetic opening basis only: no put or assignment history is implied. */
export const dramCampaign: CampaignResponse = {
  id: "dram-campaign",
  title: "DRAM covered call",
  openedOn: d("2026-09-18"),
  closedOn: null,
  notes: "Opening share basis",
  asOf: d("2026-10-01"),
  assignments: [],
  positions: [
    {
      id: "dram-stock",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "DRAM",
      strategy: "stock",
      role: "swing",
      openedOn: d("2026-09-18"),
      closedOn: null,
      notes: "Opening share basis",
      tags: [],
      legs: [
        {
          id: "dram-stock-leg",
          kind: "stock",
          side: "long",
          underlying: "DRAM",
          strike: null,
          expiry: null,
          multiplier: 1,
          adjusted: false,
          mark: null,
          trades: [
            {
              id: "dram-stock-open",
              action: "open",
              tradeDate: d("2026-09-18"),
              quantity: 1500,
              price: m("53"),
              cash: m("-79500"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
    {
      id: "dram-call",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "DRAM",
      strategy: "cc",
      role: "income",
      openedOn: d("2026-09-18"),
      closedOn: null,
      notes: null,
      tags: [],
      legs: [
        {
          id: "dram-call-leg",
          kind: "call",
          side: "short",
          underlying: "DRAM",
          strike: m("55"),
          expiry: d("2026-10-16"),
          multiplier: 100,
          adjusted: false,
          mark: null,
          trades: [
            {
              id: "dram-call-open",
              action: "open",
              tradeDate: d("2026-09-18"),
              quantity: 15,
              price: m("1.10"),
              cash: m("1650"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
  ],
};

export const aaplCampaign: CampaignResponse = {
  id: "aapl-campaign",
  title: "AAPL long call",
  openedOn: d("2026-09-10"),
  closedOn: null,
  notes: null,
  asOf: d("2026-10-01"),
  assignments: [],
  positions: [
    {
      id: "aapl-call",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "AAPL",
      strategy: "long_call",
      role: "swing",
      openedOn: d("2026-09-10"),
      closedOn: null,
      notes: null,
      tags: [],
      legs: [
        {
          id: "aapl-call-leg",
          kind: "call",
          side: "long",
          underlying: "AAPL",
          strike: m("250"),
          expiry: d("2026-11-20"),
          multiplier: 100,
          adjusted: false,
          mark: { asOf: d("2026-10-01"), price: m("5.10"), source: "manual" },
          trades: [
            {
              id: "aapl-call-open",
              action: "open",
              tradeDate: d("2026-09-10"),
              quantity: 1,
              price: m("7.80"),
              cash: m("-780"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
  ],
};

export const crwdCampaign: CampaignResponse = {
  id: "crwd-campaign",
  title: "CRWD shares",
  openedOn: d("2026-09-21"),
  closedOn: null,
  notes: null,
  asOf: d("2026-10-01"),
  assignments: [],
  positions: [
    {
      id: "crwd-stock",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "CRWD",
      strategy: "stock",
      role: "swing",
      openedOn: d("2026-09-21"),
      closedOn: null,
      notes: null,
      tags: [],
      legs: [
        {
          id: "crwd-stock-leg",
          kind: "stock",
          side: "long",
          underlying: "CRWD",
          strike: null,
          expiry: null,
          multiplier: 1,
          adjusted: false,
          mark: { asOf: d("2026-10-01"), price: m("471.30"), source: "manual" },
          trades: [
            {
              id: "crwd-stock-open",
              action: "open",
              tradeDate: d("2026-09-21"),
              quantity: 50,
              price: m("455.20"),
              cash: m("-22760"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
  ],
};

/** Isolated recorded assignment fixture, never used as the opening-basis seed. */
export const dramAssignedCampaign: CampaignResponse = {
  id: "dram-assigned-campaign",
  title: "DRAM recorded wheel",
  openedOn: d("2026-07-01"),
  closedOn: null,
  notes: null,
  asOf: d("2026-10-01"),
  assignments: [
    {
      id: "dram-assignment",
      optionTradeId: "dram-put-assign",
      stockTradeId: "dram-assigned-stock-open",
      shares: 1500,
      premiumPerShare: m("2"),
    },
  ],
  positions: [
    {
      id: "dram-put",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "DRAM",
      strategy: "csp",
      role: "income",
      openedOn: d("2026-07-01"),
      closedOn: d("2026-07-31"),
      notes: null,
      tags: [],
      legs: [
        {
          id: "dram-put-leg",
          kind: "put",
          side: "short",
          underlying: "DRAM",
          strike: m("55"),
          expiry: d("2026-07-31"),
          multiplier: 100,
          adjusted: false,
          mark: null,
          trades: [
            {
              id: "dram-put-open",
              action: "open",
              tradeDate: d("2026-07-01"),
              quantity: 15,
              price: m("2"),
              cash: m("3000"),
              fees: m("-9.90"),
            },
            {
              id: "dram-put-assign",
              action: "assign",
              tradeDate: d("2026-07-31"),
              quantity: 15,
              price: m("0"),
              cash: m("0"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
    {
      id: "dram-assigned-stock",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "DRAM",
      strategy: "stock",
      role: "swing",
      openedOn: d("2026-07-31"),
      closedOn: null,
      notes: null,
      tags: [],
      legs: [
        {
          id: "dram-assigned-stock-leg",
          kind: "stock",
          side: "long",
          underlying: "DRAM",
          strike: null,
          expiry: null,
          multiplier: 1,
          adjusted: false,
          mark: null,
          trades: [
            {
              id: "dram-assigned-stock-open",
              action: "open",
              tradeDate: d("2026-07-31"),
              quantity: 1500,
              price: m("55"),
              cash: m("-82500"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
    {
      id: "dram-assigned-call",
      revision: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      underlying: "DRAM",
      strategy: "cc",
      role: "income",
      openedOn: d("2026-09-18"),
      closedOn: null,
      notes: null,
      tags: [],
      legs: [
        {
          id: "dram-assigned-call-leg",
          kind: "call",
          side: "short",
          underlying: "DRAM",
          strike: m("55"),
          expiry: d("2026-10-16"),
          multiplier: 100,
          adjusted: false,
          mark: null,
          trades: [
            {
              id: "dram-assigned-call-open",
              action: "open",
              tradeDate: d("2026-09-18"),
              quantity: 15,
              price: m("1.10"),
              cash: m("1650"),
              fees: m("0"),
            },
          ],
        },
      ],
    },
  ],
};
