// Curated offline suggestions, not a security master or a restriction on manually entered symbols.
const SYMBOLS = `
AA AAL AAP AAPL ABBV ABNB ABT ACGL ACHR ADBE ADI ADM ADP ADSK AEE AEP AES AFL
AGNC AI AIG AIZ AJG AKAM ALB ALGN ALL ALNY AMAT AMD AME AMGN AMKR AMT AMZN
ANET AON AOS APA APD APH APLD APO APP APTV ARCC ARE ARM ASML ASTS AVB AVGO
AVTR AVY AWK AXON AXP AZO
BA BAC BAX BBY BDX BEN BILI BIIB BK BKNG BKR BLDR BLK BMY BRK.B BRO BSX BTI
BWA BX BXP
C CAG CAH CARR CAT CB CBOE CCI CCL CDNS CDW CE CEG CF CFG CHD CHRW CHTR
CI CINF CL CLF CLX CMA CMCSA CME CMG CMI CMS CNC CNP COF COHR COIN COP COR
COST CP CPAY CPB CPRT CPT CRH CRM CRWD CSCO CSGP CSX CTAS CTRA CTSH CTVA
CVS CVX
D DAL DASH DD DDOG DE DECK DEO DELL DG DGX DHI DHR DIS DLR DLTR DOC DOCN
DOCU DOV DOW DPZ DRI DTE DUK DVN DXCM
EA EBAY EC ECL ED EEM EFA EFX EG EIX EL ELV EMN EMR ENPH EOG EPAM EQIX EQR
EQT ES ESS ET ETN ETR ETSY EW EXC EXPD EXPE EXR
F FANG FAST FCX FDX FE FFIV FICO FIS FITB FSLR FTNT FTV
GD GDDY GE GEHC GEN GEV GILD GIS GL GLD GLW GM GME GNRC GOOG GOOGL GPC
GPN GRMN GS GWW
HAL HAS HBAN HCA HD HE HES HIG HII HLT HOLX HON HOOD HPE HPQ HRL HSIC
HST HSY HUBB HUM HWM
IBIT IBM ICE IDXX IEF IEX IFF IJR ILMN INCY INTC INTU INVH IONQ IP IQV IR
IRM ISRG IT ITB ITW IVV IWM
J JBHT JBL JCI JD JEF JNJ JPM
KDP KEY KEYS KHC KIM KLAC KMB KMI KMX KO KR KVUE
L LDOS LEN LH LHX LIN LKQ LLY LMT LNT LOW LRCX LULU LUV LVS LW LYB LYV
MA MAR MCD MCHP MCK MCO MDLZ MDT MELI MET META MGM MKC MLM MMM MNST MO
MOH MOS MPC MPWR MRK MRNA MRVL MS MSCI MSFT MSTR MTB MTCH MTD MU
NCLH NDAQ NDSN NEE NEM NET NFLX NIO NKE NOC NOW NRG NSC NTAP NTRS NUE
NVDA NVDL NVR NXPI
O ODFL OKE OKTA OMC ON ORCL ORLY OTIS OXY
PANW PATH PAYC PAYX PCAR PCG PEG PEP PFE PFG PG PGR PH PHM PLD PLTR PM
PNC PNR PNW PODD POOL PPG PPL PRU PSA PSX PTC PWR PYPL
QCOM QQQ QRVO
RBLX RCL REG REGN RF RIVN RJF RKT RL RMD ROK ROKU ROP ROST RSG RTX RVTY
SBAC SBUX SCHW SE SEDG SHW SIRI SJM SLB SLV SMCI SNA SNAP SNOW SNPS SO
SOFI SOLV SPG SPGI SPOT SPXL SPY SRE STE STLD STT STX STZ SWK SWKS SYF SYK
SYY
T TAP TDG TDY TEAM TECH TER TFC TGT TJX TLT TMO TMUS TNA TOST TPL TPR TQQQ
TRGP TRMB TROW TRV TSCO TSLA TSM TSN TT TTD TTWO TWLO TXN TXT
UAL UBER UDR UHS ULTA UNH UNP UPS URI USB USO
V VICI VLO VLTO VMC VRSK VRSN VRTX VST VTR VTRS VTV VZ
W WAB WAT WBD WDC WEC WELL WFC WM WMB WMT WRB WSM WST WTW WY WYNN
XEL XLB XLC XLE XLF XLI XLK XLP XLRE XLU XLV XLY XOM XYZ
YUM ZBH ZBRA ZM ZS ZTS
`
  .trim()
  .split(/\s+/)
  .sort();

export function tickerSuggestions(query: string, ownTickers: readonly string[]): string[] {
  const prefix = query.trim().toUpperCase();
  const tickers = [...ownTickers, ...SYMBOLS].map((ticker) => ticker.trim().toUpperCase());
  return [...new Set(tickers)].filter((ticker) => ticker.length > 0 && ticker.startsWith(prefix));
}

export function tagSuggestions(query: string, tags: readonly string[]): string[] {
  const prefix = query.trim().toLowerCase();
  return [...new Set(tags)].filter((tag) => tag.toLowerCase().startsWith(prefix));
}
